package Menu;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI PC
 */
public class Personel extends javax.swing.JFrame {

    /**
     * Creates new form KursOnKayit
     */
    public Personel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kurs_adi = new javax.swing.JComboBox<>();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        cep_telefonu = new javax.swing.JTextField();
        e_posta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tel Kayıt");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Bulunduğu Birim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 37));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Ad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 106, 32));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Soyad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 106, 32));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Cep Telefonu:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 106, 34));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("E-posta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 106, 32));

        kurs_adi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kurs_adi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İdari Birim", "Satınalma Birimi", "Muhasebe Birimi", "Ruhsat Birimi", "Kalite Güvence Birimi", "Pazarlama Birimi", "Bilgi İşlem Birimi", "Üretim Birimi", "Teknik Bakım Birimi", "Malzeme Yönetimi Birimi", "Güvenlik", "Hijen Birimi" }));
        kurs_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurs_adiActionPerformed(evt);
            }
        });
        getContentPane().add(kurs_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 254, 32));

        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 254, 32));

        soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soyadActionPerformed(evt);
            }
        });
        getContentPane().add(soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 254, 32));

        cep_telefonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_telefonuActionPerformed(evt);
            }
        });
        getContentPane().add(cep_telefonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 254, 34));

        e_posta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_postaActionPerformed(evt);
            }
        });
        getContentPane().add(e_posta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 254, 32));

        table.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "POZİSYON", "AD", "SOYAT", "TEL", "E-MAİL", "NOT", "İD"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 909, 520));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İMAGE/diskette_save_saveas_1514.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 150, 30));

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İMAGE/1486504830-delete-dustbin-empty-recycle-recycling-remove-trash_81361.png"))); // NOI18N
        jButton2.setText("Kayıt Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 150, 30));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İMAGE/UPDATE.png"))); // NOI18N
        jButton3.setText("Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 150, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("       --------PERSONEL----------");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 11, 364, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("NOT:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 106, 32));

        adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresActionPerformed(evt);
            }
        });
        getContentPane().add(adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 254, 66));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1299, 0, 1022, 33));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, 328));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("İd:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 106, 37));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 254, 30));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 51, 204), null, null));

        jLabel10.setText("Mustafa YALÇIN 2002.V01");

        jLabel13.setText("www.digita.educationworld@com.tr");

        jLabel12.setText("---DEW ---    Digital Education World");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 190, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Runner/ögrenci girişi.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bildirim;
        DefaultTableModel model=(DefaultTableModel) table.getModel();
            if((ad.getText().trim().equals(""))){
                bildirim="Ad boş bırakılamaz!";
                    JOptionPane.showMessageDialog(this, bildirim);
            }
            else if(soyad.getText().trim().equals("")){
                bildirim="Soyad boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
                
            }
            else if(cep_telefonu.getText().trim().equals("")){
                bildirim="Cep telefonu boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else if(e_posta.getText().trim().equals("")){
                bildirim="E-posta boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else if(adres.getText().trim().equals("")){
                bildirim="Adres Kısmı boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
             }
            else if(id.getText().trim().equals("")){
                bildirim="Adres Kısmı boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);      
            }      
            else {
Object [] dizi={kurs_adi.getSelectedItem().toString(),ad.getText(),soyad.getText(),cep_telefonu.getText(),e_posta.getText(),adres.getText(),id.getText()};
    model.addRow(dizi);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String bildirim;
    DefaultTableModel model=(DefaultTableModel)table.getModel();
        int satir=table.getSelectedRow();
            if(satir==-1){
                if(table.getRowCount()==0){
                    bildirim="Tablo'da kişi bulunmuyor.";
                    JOptionPane.showMessageDialog(this, bildirim);
                }
                else {
                    bildirim="Lütfen silmek istediğiniz satırı seçin";
                    JOptionPane.showMessageDialog(this, bildirim);
                }
            }
            model.removeRow(satir);
                   bildirim="Seçili kişi kaydı başarıyla silindi.";
                   JOptionPane.showMessageDialog(this, bildirim);
                   id.setText("");
                   ad.setText("");
                   soyad.setText("");
                   cep_telefonu.setText("");
                   e_posta.setText("");
                   adres.setText("");
                   
                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       DefaultTableModel model=(DefaultTableModel)table.getModel();
         int satir=table.getSelectedRow();
            id.setText(model.getValueAt(satir, 0).toString());
            kurs_adi.setSelectedItem(model.getValueAt(satir, 1).toString());
            ad.setText(model.getValueAt(satir, 2).toString());
            soyad.setText(model.getValueAt(satir, 3).toString());
            cep_telefonu.setText(model.getValueAt(satir, 4).toString());
            e_posta.setText(model.getValueAt(satir, 5).toString());
            adres.setText(model.getValueAt(satir, 6).toString());
           
    }//GEN-LAST:event_tableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String bildirim;
       DefaultTableModel model=(DefaultTableModel)table.getModel();
        int satir=table.getSelectedRow();
            if(satir==-1){
                if(table.getRowCount()==0){
                bildirim="Tablo'da kişi bulunmuyor.";
                JOptionPane.showMessageDialog(this, bildirim);
                }
                else {
                bildirim="Lütfen güncelleme yapmak istediğiniz satırı seçiniz";
                JOptionPane.showMessageDialog(this, bildirim);
            }
           
            }
            else {
                model.setValueAt(id.getText(), satir, 0);
                model.setValueAt(kurs_adi.getSelectedItem().toString(), satir, 1);
                model.setValueAt(ad.getText(), satir, 2);
                model.setValueAt(soyad.getText(), satir, 3);
                model.setValueAt(cep_telefonu.getText(), satir, 4);
                model.setValueAt(e_posta.getText(), satir, 5);
                model.setValueAt(adres.getText(), satir, 6);
               
                    bildirim="Kişi kaydı başarıyla güncellendi.";
                    JOptionPane.showMessageDialog(this, bildirim);
                    
                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void kurs_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurs_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurs_adiActionPerformed

    private void adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soyadActionPerformed

    private void e_postaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_postaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_postaActionPerformed

    private void cep_telefonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_telefonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_telefonuActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField adres;
    private javax.swing.JTextField cep_telefonu;
    private javax.swing.JTextField e_posta;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kurs_adi;
    private javax.swing.JTextField soyad;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
